apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      serviceAccountName: lenneflow-sa
      containers:
      - name: account-service
        image: lenneflow/account-service
        ports:
        - containerPort: 47001
        resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "1.0"
            memory: 300Mi
        readinessProbe:
            httpGet:
              port: 47001
              path: /actuator/health
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
        livenessProbe:
            httpGet:
              port: 47001
              path: /actuator/info
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
        volumeMounts:
            - name: mongodb
              mountPath: /etc/secretspot
        #            - name: config
        #              mountPath: /etc/appconfig
        env:
          - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
            value: "true"
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
            value: "true"
#          - name: SPRING_CONFIG_IMPORT
#            value: "kubernetes:"
      volumes:
        - name: mongodb
          secret:
            secretName: account-service
      #        - name: config
      #          configMap:
      #            name: department