apiVersion: v1
kind: Service
metadata:
  name: callback-service
  labels:
    app: callback-service
    spring-boot: "true"
spec:
  ports:
    - port: 47007
      protocol: TCP
  selector:
    app: callback-service
  type: ClusterIP