apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lenneflow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: lenneflow.ganemtore.bf
      http:
        paths:
          - path: /api/control
            pathType: Prefix
            backend:
              service:
                name: orchestration-service
                port:
                  number: 47002
          - path: /api/functions
            pathType: Prefix
            backend:
              service:
                name: function-service
                port:
                  number: 47003
          - path: /api/workers
            pathType: Prefix
            backend:
              service:
                name: worker-service
                port:
                  number: 47004
          - path: /api/workflows
            pathType: Prefix
            backend:
              service:
                name: workflow-service
                port:
                  number: 47005
          - path: /api/callback
            pathType: Prefix
            backend:
              service:
                name: callback-service
                port:
                  number: 47007
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 47000